Update dashboarding section for new features
infrawatch/documentation pull request #127
Opened 2020-08-26 20:28 UTC by leifmadsen

Update the dashboarding module to sync with the new functionality merged in
https://github.com/infrawatch/service-telemetry-operator/pull/115

2020-08-26 20:32 UTC, leifmadsen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update graphing section in documentation for new `graphingEnabled` functionality in STO](https://trello.com/c/tSNifSD7/1115-update-graphing-section-in-documentation-for-new-graphingenabled-functionality-in-sto)

2020-08-27 09:04 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +Grafana is not included in the default {Project} ({ProjectShort}) deployment so you must deploy the Grafana Operator from OperatorHub.io. Using the Service Telemetry Operator to deploy Grafana will r
```suggestion
Grafana is not included in the default {Project} ({ProjectShort}) deployment so you must deploy the Grafana Operator from OperatorHub.io. Using the Service Telemetry Operator to deploy Grafana results in a Grafana instance and the  configuration of the default data sources for the local {ProjectShort} deployment.
```

2020-08-27 09:04 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +and the default datasources configured for the local {ProjectShort} deployment.
```suggestion
```

2020-08-27 09:04 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +Enable OperatorHub.io catalog source for the Grafana Operator. See xref:enabling-the-operatorhubio-community-catalog-source[].
```suggestion
Enable OperatorHub.io catalog source for the Grafana Operator. For more information, see xref:enabling-the-operatorhubio-community-catalog-source[].
```

2020-08-27 09:05 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
>  [discrete]
```suggestion
```

2020-08-27 09:10 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +. Launch a Grafana instance by creating or modifying the `ServiceTelemetry` object. Set `graphingEnabled` to `true`.
```suggestion
. To launch a Grafana instance, create or modify the `ServiceTelemetry` object. Set `graphingEnabled` to `true`.
```

2020-08-27 09:12 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +[discrete]
```suggestion
```

2020-08-27 09:12 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +[discrete]
```suggestion
```

2020-08-27 09:14 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
>  [discrete]
```suggestion
```

2020-08-27 09:20 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +* For more information about enabling the OperatorHub.io catalog source, see xref:enabling-the-operatorhubio-community-catalog-source[].
```suggestion

```

2020-08-27 09:20 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +.Additional resources
```suggestion

```

2020-08-27 09:20 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +.Additional resources
We can remove this section as it's already in the Prereqs above

2020-08-27 09:28 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +Dashboards can be imported and managed by the Grafana Operator by creating `GrafanaDashboard` objects. Example dashboards are provided at https://github.com/infrawatch/dashboards.
```suggestion
The Grafana Operator can import and manage dashboards by creating `GrafanaDashboard` objects. You can view example dashboards at https://github.com/infrawatch/dashboards.
```

2020-08-27 09:32 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +. Expose the grafana service as a route
```suggestion
. Expose the grafana service as a route:
```

2020-08-27 09:34 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
> +. Import a dashboard.
```suggestion
. Import a dashboard:
```

2020-08-27 09:35 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
>  . Navigate to https://<grafana-route-address> in a web browser. Use the `oc get routes` command to retrieve the Grafana route address:
```suggestion
. Navigate to https://<grafana-route-address> in a web browser. 

. Use the `oc get routes` command to retrieve the Grafana route address:
```

2020-08-27 09:41 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
>  . Navigate to https://<grafana-route-address> in a web browser. Use the `oc get routes` command to retrieve the Grafana route address:
@leifmadsen Apologies if this came up previously. How can one navigate to an address that they do not have yet? 
Should this be separated out, something like: 

. Use the `oc get routes` command to retrieve the Grafana route address:
**comand and output blah**
The HOST/PORT value is the Grafana route address. 
. Navigate to https://<grafana-route-address> in a web browser. Replace <grafana-route-address> with the HOST/PORT value you retrieved in the previous step.

2020-08-27 09:43 UTC, JoanneOFlynn2018 requested changes
I committed minor edits and left suggested edits/comments on anything else I thought you would like to see!

2020-08-27 16:37 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_setting-up-grafana-to-host-the-dashboard.adoc
>  . Navigate to https://<grafana-route-address> in a web browser. Use the `oc get routes` command to retrieve the Grafana route address:
Ah ha, yes, that sounds right. Use `oc get routes` to obtain the address first, then navigate to https://<value from HOST/PORT>.

2020-08-27 16:37 UTC, leifmadsen commented
All changes from @JoanneOFlynn2018 look good to me, and I've merged those into the PR. Looks like just the one outstanding change to do.

2020-08-31 19:39 UTC, JoanneOFlynn2018 approved these changes

2020-08-31 19:46 UTC, merged