Add explanation for enabling libpodstats
infrawatch/documentation pull request #133
Opened 2020-10-22 19:21 UTC by pleimer

Add a section explaining how to enable the gathering of service container metrics in the overcloud.

2020-10-22 19:22 UTC, pleimer commented
I don't think my link to stf-connectors.yaml is working correctly at the moment

2020-10-22 19:35 UTC, leifmadsen submitted a review, later dismissed

2020-10-22 19:35 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_service-resource-usage-metrics.adoc
> +// include::<path>/con_manifest-overrides.adoc[leveloffset=+1]
```suggestion
// include::<path>/con_advanced-features.adoc [leveloffset=+1]
```

2020-10-22 19:35 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_service-resource-usage-metrics.adoc
> +Metrics pertaining to the resource usage of individual service contianers within an overcloud are not enabled by default. To gather these metrics, set `CollectdEnableLibpodstats: true` in the xref:co
So the `con` is for concept, so this file should be discussing the concept or the "what" a _Service resource usage metric_ is. If I was going to read this title I wouldn't really know what it meant or why I might look at it.

After the concept module, you'll create a `proc` or process module. The process module is for the actual work items you'd perform to enable this functionality. These process modules should be able to stand on their own, or link back to other process modules you might follow to get to this point.

The process will be fairly straight forward, but check out some of the other `proc` modules for a format of what you might do there. Process is probably just something like:

. Modify your `stf-connectors.yaml`. See [...] for more information about creating the `stf-connectors.yaml`.
. Add `CollectdEnableLibpodstats: true`
```
---
parameter_defaults:
  ...
  CollectdEnableLibpodstats: true
```

Or something like that. In the concept module I would also talk about any dependencies, and give an idea about what kinds of stats you might get, and why you might want this module enabled.

2020-10-22 19:35 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_service-resource-usage-metrics.adoc
> +Metrics pertaining to the resource usage of individual service contianers within an overcloud are not enabled by default. To gather these metrics, set `CollectdEnableLibpodstats: true` in the xref:co
```suggestion
Metrics pertaining to the resource usage of individual service containers within an overcloud are not enabled by default. To gather these metrics, set `CollectdEnableLibpodstats: true` in the xref:configuring-red-hat-openstack-platform-overcloud-for-stf[stf-connectors.yaml] when deploying the overcloud.
```

2020-10-22 19:36 UTC, leifmadsen commented
You also need to include your module in doc-Service-Telemetry-Framework/assemblies/assembly_advanced-features.adoc

2020-10-22 19:37 UTC, leifmadsen commented
```
diff --git a/doc-Service-Telemetry-Framework/assemblies/assembly_advanced-features.adoc b/doc-Service-Telemetry-Framework/assemblies/assembly_advanced-features.adoc
index 65c1486..6cd450c 100644
--- a/doc-Service-Telemetry-Framework/assemblies/assembly_advanced-features.adoc
+++ b/doc-Service-Telemetry-Framework/assemblies/assembly_advanced-features.adoc
@@ -69,3 +69,6 @@ include::../modules/proc_querying-metrics-data-from-multiple-clouds.adoc[levelof
 //Configuring ephemeral storage
 include::../modules/con_ephemeral-storage.adoc[leveloffset=+1]
 include::../modules/proc_configuring-ephemeral-storage.adoc[leveloffset=+2]
+
+//Service resource usage metrics
+include::../modules/con_service-resource-usage-metrics.adoc[leveloffset=+1]
```

2020-10-22 19:52 UTC, pleimer commented on doc-Service-Telemetry-Framework/modules/con_service-resource-usage-metrics.adoc
> +Metrics pertaining to the resource usage of individual service contianers within an overcloud are not enabled by default. To gather these metrics, set `CollectdEnableLibpodstats: true` in the xref:co
Ah I see thanks

2020-10-23 15:25 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/con_service-resource-usage-metrics.adoc
> +Monitoring the resource usage of the openstack services such as the APIs and other infrastructure processes can be very useful in identifying areas of the cloud that are under a lot of stress. This c
@pleimer This is a really good intro, thanks Paul. Knowing the why is super important. And thank you for including a prerequisite and procedure below. I will go through this later and apply RH docs style to it.

2020-10-23 15:29 UTC, pleimer commented on doc-Service-Telemetry-Framework/modules/con_service-resource-usage-metrics.adoc
> +Monitoring the resource usage of the openstack services such as the APIs and other infrastructure processes can be very useful in identifying areas of the cloud that are under a lot of stress. This c
Thanks Joanne!

2020-10-28 12:24 UTC, JoanneOFlynn2018 approved these changes

2020-10-28 13:25 UTC, leifmadsen commented
I'm going to get this merged down and imported in to the STF 1.1 documentation updates. If for some reason this misses 16.1.3 we'll need to comment it out downstream, but that's not a huge deal for upstream master docs.

2020-10-28 13:43 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-resource-usage-of-openstack-services.adoc
> +```
Does this actually load appropriately? This is markdown syntax :)

2020-10-28 13:44 UTC, leifmadsen requested changes

2020-10-28 13:44 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-resource-usage-of-openstack-services.adoc
> +```
```suggestion
----
  CollectdEnableLibpodstats: true
----
```

2020-10-28 13:45 UTC, leifmadsen commented
Did a local build and check, and this all loads fine. Merging!

2020-10-28 13:46 UTC, leifmadsen approved these changes

2020-10-28 13:46 UTC, merged