Pleimer api stats
infrawatch/documentation pull request #146
Opened 2020-12-21 16:34 UTC by pleimer

Here are the amendments for the 'monitoring container healthchecks and api stats' feature. I included a new module that should go in the 'Advanced Features' section as a markdown file (sorry, no adoc). There are also some adjustments made to the multi-cloud section. All of these features are only available in train/osp16.1.3/STF1.1

2021-01-04 18:41 UTC, leifmadsen requested changes
Also need to change doc-Service-Telemetry-Framework/modules/api-stats-updates.md to be an asciidoc file (.adoc). Will need to create appropriate label to be able to xref it in doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +To monitor healthchecks in STF, the collectd-sensubility plugin must be enabled
```suggestion
To monitor healthchecks in {ProjectShort}, the collectd-sensubility plugin must be enabled 
```

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +Container health assesses the status of each of the OpenStack service containers
```suggestion
Container health assesses the status of each of the {OpenStack} service containers
```

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +Most OpenStack services implement a healthcheck that logs issues and returns a
```suggestion
Most {OpenStack} services implement a healthcheck that logs issues and returns a
```

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +and configured to work with the amqp1 protocol. The STF architecture considers
```suggestion
and configured to work with the amqp1 protocol. The {ProjectShort} architecture considers
```

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +- You have created the stf-connectors.yaml file. For more information, see Configuring OpenStack overcloud for Service Telemetry Framework.
```suggestion
- You have created the `stf-connectors.yaml` file. For more information, see xref:configuring-red-hat-openstack-platform-overcloud-for-stf_completing-the-stf-configuration[].
```

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +- You are using the most current version of OpenStack: Train.
```suggestion
- You are using the most current version of {OpenStack} {OpenStackVersion}.
```

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +Within the stf-connectors.yaml, configure collectd-sensubility to use the amqp1
```suggestion
Within the `stf-connectors.yaml`, configure collectd-sensubility to use the amqp1
```

2021-01-04 18:41 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/api-stats-updates.md
> +to be adjusted in  accordance with the new collectd events address. See the [Multiple cloud configuration](https://infrawatch.github.io/documentation/#configuring-multiple-clouds_advanced-features)
```suggestion
to be adjusted in accordance with the new collectd events address. For more information, see xref:configuring-multiple-clouds_advanced-features[]
```

2021-01-04 18:43 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +To label traffic according to the cloud of origin, you must create a configuration with cloud-specific instance names. Create an `stf-connectors.yaml` file and adjust the values of `CeilometerQdrEven
Should probably convert this to a NOTE or IMPORTANT. Also need to make sure we update the `OSP` to `{OpenStack}` and update the missing reference (link) to an `xref` of the appropriate header.

2021-01-18 08:58 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +. If you have a multicloud environment, you must configure `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```suggestion
. If  your environment has multiple clouds, configure `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```

2021-01-18 09:01 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +by periodically running a health check script using the docker standard.
Leif's comment from previous PR: Should Docker be capitalized? Also we're using podman in 16.1 so I think the more correct term is OCI? (Open Container Initiative)

I'm not actually sure what the correct term is here. @csibbitt do you know?

2021-01-18 09:03 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +by periodically running a health check script using the docker standard.
@mcljot do you know if the correct term is OCI (Open Container Initiative)?

2021-01-19 13:47 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +by periodically running a health check script using the docker standard.
Update, @mcljot and myself both didn't know the answer to this. After some research, I think OCI is the correct term. @csibbitt if you would like to concur, that would be great

And for completeness @leifmadsen, when we refer to Docker and Podman in conceptual text (not commands), yes  the first letters should be capitalizied. Thanks for bringing that up, good to know for future work :)

2021-01-19 13:51 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +by periodically running a health check script using the docker standard.
Update, @mcljot and myself both didn't know the answer to this. After some research, I think OCI is the correct term. @csibbitt if you would like to concur, that would be great

And for completeness @leifmadsen, when we refer to Docker and Podman in conceptual text (not commands), yes  the first letters should be capitalizied. Thanks for bringing that up, good to know for future work :)

2021-01-19 13:52 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +[id="monitoring-container-health-and-api-status_{context}"]
@pleimer Hi Paul, 
I converted this file to asciidoc and edited it. Can you perform a review of all of the text in this file? Thanks!

2021-01-19 13:55 UTC, pleimer commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +[id="monitoring-container-health-and-api-status_{context}"]
I will, thanks for doing the conversion!

2021-01-19 18:30 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +by periodically running a health check script using the docker standard.
I think we can move forward using OCI. Thanks!

2021-01-19 19:56 UTC, pleimer commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +by periodically running a health check script using the docker standard.
OCI seems like the correct term

2021-01-19 19:57 UTC, pleimer reviewed
Everything looks good to me!

2021-01-21 09:41 UTC, JoanneOFlynn2018 requested changes
Have made suggestions but cannot commit them. Submitting review and trying again.

2021-01-21 09:41 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +To label traffic according to the cloud of origin, you must create a configuration with cloud-specific instance names. Create an `stf-connectors.yaml` file and adjust the values of `CeilometerQdrEven
```suggestion
To label traffic according to the cloud of origin, you must create a configuration with cloud-specific instance names. Create an `stf-connectors.yaml` file and adjust the values of `CeilometerQdrEventsConfig`, `CeilometerQdrMetricsConfig` and `CollectdAmqpInstances` to match the AMQP address prefix scheme. 

//[OSP16.1.3+ ONLY] 
[NOTE]
If you have enabled Container health and API stats monitoring, you must also modify the `CollectdSensubilityResultsChannel` parameter. For more information, see xref:planning-amqp-address-prefixes_advanced-features[].
```

2021-01-21 09:45 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +//[OSP16.1.3+ ONLY]
@leifmadsen In the customer portal, we still don't publish z stream releases so the best I can do here is put an include_when_16 on it. In fact, there's no point in that either as master will never be synced with v13 or v16. Thoughts?

2021-01-21 09:54 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +If you have enabled Container health and API stats monitoring, you must also modify the `CollectdSensubilityResultsChannel` parameter. For more information, see xref:planning-amqp-address-prefixes_ad
```suggestion
If you have enabled Container health and API stats monitoring, you must also modify the `CollectdSensubilityResultsChannel` parameter. For more information, see xref:planning-amqp-address-prefixes_advanced-features[] and xref:monitoring-container-health-and-api-status_advanced-features[]. 
```

2021-01-21 10:08 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +//[OSP16.1.3+ ONLY]
@leifmadsen 
See step one of the procedure below:
1. Create the `stf-connectors.yaml` file
I think we should tell users where to create the file. Tech support has brought this issue up in other docs.

2021-01-21 14:49 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +If you have enabled Container health and API stats monitoring, you must also modify the `CollectdSensubilityResultsChannel` parameter. For more information, see xref:planning-amqp-address-prefixes_ad
```suggestion
If you have enabled container health and API statistics monitoring, you must also modify the `CollectdSensubilityResultsChannel` parameter. For more information, see xref:planning-amqp-address-prefixes_advanced-features[] and xref:monitoring-container-health-and-api-status_advanced-features[]. 
```

2021-01-21 14:50 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +If you have enabled Container health and API stats monitoring, you must also modify the `CollectdSensubilityResultsChannel` parameter. For more information, see xref:planning-amqp-address-prefixes_ad
```suggestion
If you have enabled container health and API status monitoring, you must also modify the `CollectdSensubilityResultsChannel` parameter. For more information, see xref:planning-amqp-address-prefixes_advanced-features[] and xref:monitoring-container-health-and-api-status_advanced-features[]. 
```

2021-01-21 14:50 UTC, JoanneOFlynn2018 approved these changes

2021-01-21 14:53 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +* You have created the `stf-connectors.yaml` file. For more information, see xref:configuring-red-hat-openstack-platform-overcloud-for-stf_completing-the-stf-configuration[].
```suggestion
* You have created the `stf-connectors.yaml` file in your templates directory. For more information, see xref:configuring-red-hat-openstack-platform-overcloud-for-stf_completing-the-stf-configuration[].
```

2021-01-21 14:53 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +. Open the `stf-connectors.yaml` and edit the `collectd-sensubility` paramater:
```suggestion
. Open the `stf-connectors.yaml` and edit the `collectd-sensubility` parameter:
```

2021-01-21 14:53 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +. If  your environment has multiple clouds, configure `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```suggestion
. If your environment has multiple clouds, configure `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```

2021-01-21 14:54 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +. If  your environment has multiple clouds, configure `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```suggestion
. If  your environment has multiple clouds, configure the `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```

2021-01-21 14:55 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +. If  your environment has multiple clouds, configure the `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```suggestion
. If your environment has multiple clouds, configure the `collectd-sensubility` events channel with the new collectd events address. Edit the `stf-connectors.yaml` file:
```

2021-01-21 14:55 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_monitoring-container-health-and-api-status.adoc
> +For more information about multi-cloud addresses, see xref:configuring-multiple-clouds_advanced-features[].
```suggestion
For more information about multiple cloud addresses, see xref:configuring-multiple-clouds_advanced-features[].
```

2021-01-21 14:59 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_creating-openstack-environment-file.adoc
> +//[OSP16.1.3+ ONLY]
```suggestion
```

2021-01-21 14:59 UTC, leifmadsen approved these changes

2021-01-21 15:05 UTC, merged