1089 how expose prom route
infrawatch/documentation pull request #152
Opened 2021-01-12 17:02 UTC by leifmadsen

- Add documentation about exposing routes
- Fix issues with wrapping

2021-01-12 17:03 UTC, leifmadsen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add instructions to expose Prometheus route in STF documentation](https://trello.com/c/RWAvjm4O/1089-add-instructions-to-expose-prometheus-route-in-stf-documentation)

2021-01-12 17:50 UTC, csibbitt approved these changes

2021-01-12 17:50 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +In {OpenShift} ingress traffic for applications is done by exposed services and accessing the application via a route. For more information about Configuring ingress cluster traffic, see https://docs
I find the first sentence hard to parse. How about something a bit simpler, like "In {OpenShift}, applications can be exposed to the external network via a route."

2021-01-12 22:18 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +In {OpenShift} ingress traffic for applications is done by exposed services and accessing the application via a route. For more information about Configuring ingress cluster traffic, see https://docs
```suggestion
In {OpenShift}, you can expose applications to the external network via a route. For more information, see https://docs.openshift.com/container-platform/{SupportedOpenShiftVersion}/networking/configuring_ingress_cluster_traffic/overview-traffic.html[Configuring ingress cluster traffic].
```

I agree with @csibbitt and I like his suggested edit.

2021-01-12 22:20 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +By default in {Project} routes are not exposed in order to limit the attack surface of {ProjectShort} deployments. In order to access some services deployed in {ProjectShort} the services in {OpenShi
```suggestion
Routes are not exposed by default in {Project} to limit the attack surface of {ProjectShort} deployments. To access some services deployed in {ProjectShort}, you must expose the services in {OpenShiftShort} for access.
```

2021-01-12 22:23 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +The way services are exposed can be environment specific, but a common service to expose in {ProjectShort} is Prometheus.
```suggestion
A common service to expose in {ProjectShort} is Prometheus, as shown in the following example:
```

2021-01-12 22:23 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +. List the available services in the `service-telemetry` project
```suggestion
. List the available services in the `service-telemetry` project:
```

2021-01-12 22:25 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +. Note the port and service name to expose as a route to allow for external access, for example service `prometheus-operated` and port `9090`
```suggestion
. Take note of the port and service name to expose as a route, for example, service `prometheus-operated` and port `9090`.
```

2021-01-12 22:25 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +. Expose the `prometheus-operated` service as an edge route and redirect insecure traffic to the secure endpoint of port `9090`
```suggestion
. Expose the `prometheus-operated` service as an edge route and redirect insecure traffic to the secure endpoint of port `9090`:
```

2021-01-12 22:26 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +. To verify and find the exposed external DNS for the route use the `oc get route` command
```suggestion
. To verify and find the exposed external DNS for the route, use the `oc get route` command:
```

2021-01-12 22:28 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +. The `prometheus-operated` service will now be avalable at the exposed DNS address, e.g. https://metrics-store-service-telemetry.apps.infra.watch
```suggestion
+
The `prometheus-operated` service is now available at the exposed DNS address, for example, https://metrics-store-service-telemetry.apps.infra.watch
```

2021-01-12 22:31 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/master.adoc
> += Service Telemetry Framework
```suggestion
= Service Telemetry Framework {ProductVersion}
```

Can we include the version here so that the titles match with Pantheon titles?

2021-01-12 22:31 UTC, JoanneOFlynn2018 requested changes
Some very minor points for you to look over

2021-01-13 02:50 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/master.adoc
> += Service Telemetry Framework
Unfortunately this doesn't work because the `stf-attributes.yml` file is included after that part of the `master.adoc`. I tried to move it further up, but it fails. We'll probably just have to manually adjust that unfortunately.

2021-01-13 02:50 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/master.adoc
> += Service Telemetry Framework
```suggestion
= Service Telemetry Framework 1.2
```

2021-01-13 02:50 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +In {OpenShift} ingress traffic for applications is done by exposed services and accessing the application via a route. For more information about Configuring ingress cluster traffic, see https://docs
Thanks! I wrote this really fast and did not review like I would normally do and instead relied on our awesome team to fix it :)

2021-01-13 02:50 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +In {OpenShift} ingress traffic for applications is done by exposed services and accessing the application via a route. For more information about Configuring ingress cluster traffic, see https://docs
Will review tomorrow thanks for picking this out. As noted earlier I didn't do my normal 2nd and 3rd readings and just brain dumped.

2021-01-13 19:34 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_exposing-routes.adoc
> +In {OpenShift} ingress traffic for applications is done by exposed services and accessing the application via a route. For more information about Configuring ingress cluster traffic, see https://docs
Ah sweet Joanne already fixed this :)

2021-01-13 19:35 UTC, leifmadsen commented
@JoanneOFlynn2018 I think this is ready to go now.

Thanks everyone!

2021-01-14 15:47 UTC, JoanneOFlynn2018 approved these changes

2021-01-14 15:48 UTC, merged