Updates for new sensubility amqp1 address
infrawatch/documentation pull request #239
Opened 2021-07-07 21:21 UTC by pleimer

last few changes that ensure docs properly describe sensubility metrics in the stf architecture

2021-07-07 23:08 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
> +By default, {OpenStack} nodes get data through three data collectors; collectd, Ceilometer. The collectd-sensubility plugin requires a unique address as if it was a separate collector. These componen
What's the third? :)

2021-07-07 23:10 UTC, leifmadsen requested changes

2021-07-07 23:10 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
> +By default, OpenStack nodes get data through two data collectors; collectd and Ceilometer. These components send telemetry data or notifications to the respective AMQP addresses, for example, collect
```suggestion
By default, OpenStack nodes get data through two data collectors; collectd and Ceilometer. These components send telemetry data or notifications to the respective AMQP addresses, for example, collectd/telemetry, where {ProjectShort} Smart Gateways listen on those addresses for monitoring data. To support multiple clouds and to identify which cloud generated the monitoring data, configure each cloud to send data to a unique address. Prefix a cloud identifier to the second part of the address. The following list shows some example addresses and identifiers:
```

2021-07-08 12:28 UTC, pleimer commented on doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
> +By default, {OpenStack} nodes get data through three data collectors; collectd, Ceilometer. The collectd-sensubility plugin requires a unique address as if it was a separate collector. These componen
I originally listed collectd-sensubility as one, looks like I forgot to change the number back!

2021-07-08 12:52 UTC, leifmadsen approved these changes

2021-07-09 11:26 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-smart-gateways.adoc
> +You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, one for Ceilometer metrics, one for Ceilometer events and one
```suggestion
You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, one for Ceilometer metrics, one for Ceilometer events, and one for collectd-sensubility metrics. Configure each of the Smart Gateways to listen on the AMQP address that you define for the corresponding cloud. To  define Smart Gateways, you configure the `clouds` parameter in the `ServiceTelemetry` manifest.
```

2021-07-09 11:27 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-smart-gateways.adoc
> +You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, one for Ceilometer metrics, one for Ceilometer events. Configu
```suggestion
You must deploy a Smart Gateway for each of the data collection types for each cloud; one for collectd metrics, one for collectd events, one for Ceilometer metrics, and one for Ceilometer events. Configure each of the Smart Gateways to listen on the AMQP address that you define for the corresponding cloud. To define Smart Gateways, configure the `clouds` parameter in the `ServiceTelemetry` manifest.
```

Removed passive voice

2021-07-09 11:32 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
> +By default, {OpenStack} nodes get data through two data collectors; collectd and Ceilometer. The collectd-sensubility plugin requires a unique address as if it was a separate collector. These compone
```suggestion
By default, {OpenStack} nodes receive data through two data collectors; collectd and Ceilometer. The collectd-sensubility plugin requires a unique address. These components send telemetry data or notifications to the respective AMQP addresses, for example, `collectd/telemetry`. {ProjectShort} Smart Gateways listen on those AMQP addresses for monitoring data. To support multiple clouds and to identify which cloud generated the monitoring data, configure each cloud to send data to a unique address. Add a cloud identifier prefix to the second part of the address. The following list shows some example addresses and identifiers:
```
Changed "get" to receive. Maybe the word "collect" is more appropriate?
Deleted this part because it will be difficult for translators and is it vital information anyway?: "as if it was a separate collector"

2021-07-09 11:33 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
> +By default, OpenStack nodes get data through two data collectors; collectd and Ceilometer. These components send telemetry data or notifications to the respective AMQP addresses, for example, collect
```suggestion
By default, {OpenStack} nodes get data through two data collectors; collectd and Ceilometer. These components send telemetry data or notifications to the respective AMQP addresses, for example, collectd/telemetry. {ProjectShort} Smart Gateways listen on the AMQP addresses for monitoring data. To support multiple clouds and to identify which cloud generated the monitoring data, configure each cloud to send data to a unique address. Add a cloud identifier prefix to the second part of the address. The following list shows some example addresses and identifiers:
```

2021-07-09 11:34 UTC, JoanneOFlynn2018 submitted a review, later dismissed
Couple of minor edits for you to review

2021-07-12 12:46 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
> +By default, {OpenStack} nodes get data through two data collectors; collectd and Ceilometer. The collectd-sensubility plugin requires a unique address as if it was a separate collector. These compone
This is good with me. @pleimer ?

2021-07-12 14:10 UTC, pleimer commented on doc-Service-Telemetry-Framework/modules/proc_planning-amqp-address-prefixes.adoc
> +By default, {OpenStack} nodes get data through two data collectors; collectd and Ceilometer. The collectd-sensubility plugin requires a unique address as if it was a separate collector. These compone
works for me

2021-07-12 14:16 UTC, merged