2129094 stf cleanup
infrawatch/documentation pull request #393
Opened 2022-09-22 14:39 UTC by JoanneOFlynn2018

2022-09-22 15:50 UTC, leifmadsen approved these changes
Looks good to me! Made a few suggestions since this is going to be the STF 1.5 documentation target.

2022-09-22 15:50 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/docinfo.xml
> +<subtitle>Installing and deploying Service Telemetry Framework 1.4</subtitle>
```suggestion
<title>Service Telemetry Framework 1.5</title>
<subtitle>Installing and deploying Service Telemetry Framework 1.5</subtitle>
```

2022-09-22 15:50 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/docinfo.xml
> +      Install the core components and deploy Service Telemetry Framework 1.4
```suggestion
      Install the core components and deploy Service Telemetry Framework 1.5
```

2022-09-22 15:50 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/master.adoc
> += Service Telemetry Framework 1.4
```suggestion
= Service Telemetry Framework 1.5
```

2022-09-26 13:06 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/master.adoc
> +//endif::[]
I would just delete this entire stanza. No need to comment it out.

2022-09-26 13:09 UTC, leifmadsen requested changes
A few changes to make here. Since this is going against master, we're targeting 17.0 and STF 1.5 for this branch.

2022-09-26 13:09 UTC, leifmadsen commented on common/global/stf-attributes.adoc
>  :ProductVersion: 1.4
```suggestion
:ProductVersion: 1.5
```

2022-09-26 16:43 UTC, rheslop commented on README.md
> +Alternatively, to make the "make" utility available on PATH, you can install the XCode development environment.
Recommend:  'Alternatively, you can install the XCode development environment so that the "make" utility is available on PATH.
Just to avoid the 'make the make utility' phrasing, although I can see this wasn't a part of the commit. It's up to you.

2022-09-26 16:43 UTC, rheslop commented on README.md
> +variable called build. You can set the value of build to either "downstream" or
```suggestion
variable called `build`. You can set the value of build to either "downstream" or
```
I'm sure the standard is different for upstream, but thought I might tag it just in case.

2022-09-26 16:54 UTC, rheslop commented on README.md
> +To build and open PDF version, enter the following command:
Several instances of "open X version" instead of "open an X version" or "open the X version of..." It looks like an article is missing.

2022-09-26 17:01 UTC, JoanneOFlynn2018 commented on common/global/stf-attributes.adoc
>  :ProductVersion: 1.4
Can I leave it at 1.4 for our downstream doc?

2022-09-26 17:08 UTC, leifmadsen commented on common/global/stf-attributes.adoc
>  :ProductVersion: 1.4
Downstream is fine, but in the upstream repo the `master` branch should target 1.5 so when we import the next release we don't miss anything. None of these changes should be getting pulled into downstream at this point right?

2022-09-27 08:32 UTC, JoanneOFlynn2018 commented on common/global/stf-attributes.adoc
>  :ProductVersion: 1.4
None of these changes *need* to be pulled downstream but when I merge this PR and the other PR re disconnected proxy, then I do need to sync with downstream repo.

But I can leave the version at 1.5 and change manually when I sync.

2022-09-27 08:55 UTC, JoanneOFlynn2018 commented on README.md
> +Alternatively, to make the "make" utility available on PATH, you can install the XCode development environment.
```suggestion
Alternatively, you can install the XCode development environment so that the "make" utility is available on PATH.
```

2022-09-27 08:56 UTC, JoanneOFlynn2018 commented on README.md
> +To build and open PDF version, enter the following command:
```suggestion
To build and open a PDF version, enter the following command:
```

2022-09-27 11:57 UTC, JoanneOFlynn2018 commented on README.md
> +HTML version and to view it in a new tab in a browser, enter the following commands:
```suggestion
a HTML version and to view it in a new tab in a browser, enter the following commands:
```

2022-09-27 11:58 UTC, JoanneOFlynn2018 commented on README.md
>  make both formats in one command, use `make html pdf`. To build downstream
```suggestion
make both formats in one command, use `make html pdf`. To build a downstream
```

2022-09-27 12:00 UTC, JoanneOFlynn2018 commented on README.md
> +version perform `make BUILD=downstream browser`.
```suggestion
version, run the `make BUILD=downstream browser` command.
```

2022-09-27 12:17 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/master.adoc
> +//ifeval::["{build}" == "upstream"]
```suggestion
```

2022-09-27 12:17 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/master.adoc
> +//include::common/collectd/ref_collectd-plugins.adoc[leveloffset=+1]
```suggestion
```

2022-09-27 12:17 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/master.adoc
> +//endif::[]
```suggestion
```

2022-09-27 12:47 UTC, leifmadsen approved these changes

2022-09-27 12:59 UTC, merged