mg_master_2168184_adding section with procedures for upgrade from 1.4…
infrawatch/documentation pull request #444
Opened 2023-02-09 12:37 UTC by mickogeary

… to 1.5

2023-02-09 13:17 UTC, JoanneOFlynn2018 commented
I'm not sure why the build fails, everything is fine when I build locally.

2023-02-09 13:19 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Back up your data. There is an outage during the Red Hat OpenShift Container Platform upgrade. You cannot reconfigure the `ServiceTelemetry` and `SmartGateway` objects during the Operators replacem
```suggestion
* You have backed up your data. There is an outage during the Red Hat OpenShift Container Platform upgrade. You cannot reconfigure the `ServiceTelemetry` and `SmartGateway` objects during the Operators replacement.
```

Edit each of the prereqs to be parallel with the tense here. Prereqs are things you must already have or tasks you must have already performed.

2023-02-09 13:20 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +You must remove AMQ Certificate Manager and replace it with Certificate Manager for Red Hat OpenShift Container Platform when you upgrade Service Telemetry Framework (STF) v1.4 to STF v1.5. You must
```suggestion
You must remove AMQ Certificate Manager and replace it with Certificate Manager for Red Hat OpenShift Container Platform when you upgrade {Project} ({ProjectShort}) v1.4 to {ProjectShort} v1.5. You must remove the `ClusterServiceVersion` and `Subscription` objects for Smart Gateway Operator and Service Telemetry Operator in the `service-telemetry` namespace on your Red Hat OpenShift Container Platform environment. You must upgrade Red Hat OpenShift Container Platform from v4.8 to v4.10 before you re-enable the operators that you removed.
```

{Project} = Service Telemetry Framework 
{ProjectShort} = STF

Attributes are in the readme.

2023-02-09 13:22 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +. Removing the STF v1.4 Operators
```suggestion
. Removing the STF v1.4 Operators
```

Because we are not allowed to have xrefs here :( you can remove the gerunds from the steps.

2023-02-09 13:25 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +* Your Red Hat OpenShift Container Platform environment network is fully-connected.
```suggestion
* Your Red Hat OpenShift Container Platform environment network is fully connected.
```

Remove hyphen

2023-02-09 13:26 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +. Optional: For information on how to re-subscribe to the Grafana Operator, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/service_telemetry_framework_1.
```suggestion
. Optional: Resubscribe to the Grafana Operator. For more information, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/service_telemetry_framework_1.5/assembly-advanced-features_assembly#setting-up-grafana-to-host-the-dashboard_assembly-advanced-features[Configuring Grafana to host the dashboard].
```

2023-02-09 14:44 UTC, leifmadsen commented
> I'm not sure why the build fails, everything is fine when I build locally.

Huh builds for me as well locally. Let me look at the build system itself. I might have to try and reproduce it locally here, but we'll see.

2023-02-09 14:46 UTC, leifmadsen commented
> > I'm not sure why the build fails, everything is fine when I build locally.
> 
> Huh builds for me as well locally. Let me look at the build system itself. I might have to try and reproduce it locally here, but we'll see.

Ahhhh I see the problem. Looks like the Fedora 33 base image I was using for the build system is gone now (F33 no longer receiving updates and is EOL I suppose). I will need to update to a newer base image. Might take me a bit, but I'll get it figured out. Nothing appears to be wrong with the actual asciidoc here though.

`docker: Error response from daemon: unknown: Tag 33-x86_64 was deleted or has expired. To pull, revive via time machine.`

2023-02-09 15:27 UTC, leifmadsen commented
I fixed the build issue in https://github.com/infrawatch/documentation/pull/445 and will merge it into this PR once it has been approved and merged to master.

2023-02-09 15:48 UTC, JoanneOFlynn2018 commented
> I fixed the build issue in #445 and will merge it into this PR once it has been approved and merged to master.

Nice one Leif!

2023-02-09 18:06 UTC, rheslop commented on doc-Service-Telemetry-Framework/modules/proc_upgrading-red-hat-openshift-container-platform-to-v4-10.adoc
> +* You removed the AMQ Certificate Manager Operator and Grafana Operator. You must remove the Operators before you upgrade Red Hat OpenShift Container Platform because the Operator APIs are incompatib
```suggestion
* You removed the AMQ Certificate Manager Operator and Grafana Operator. You must remove the Operators before you upgrade Red Hat OpenShift Container Platform because the Operator APIs are incompatible with v4.10. For more information about preparing your Red Hat OpenShift Container Platform for upgrade from v4.8 to v4.10, see link:https://docs.openshift.com/container-platform/4.8/updating/understanding-openshift-updates.html[Understanding OpenShift Container Platform updates].
```
The link does work both ways, but also appears to work with any number of arbitrary slashes

2023-02-09 19:48 UTC, rheslop commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +You must remove AMQ Certificate Manager and replace it with Certificate Manager for Red Hat OpenShift Container Platform when you upgrade Service Telemetry Framework (STF) v1.4 to STF v1.5. You must
```suggestion
When you upgrade {Project} ({ProjectShort}) v1.4 to {ProjectShort} v1.5, you must complete the following steps. 
* Replace AMQ Certificate Manager with Certificate Manager.
* Remove the `ClusterServiceVersion` and `Subscription` objects for Smart Gateway Operator and Service Telemetry Operator.
* Upgrade Red Hat OpenShift Container Platform from v4.8 to v4.10, and then re-enable the operators that you removed.
```
The three 'musts' in a row are a bit much, the way it reads I wanted to link the bullet points to processes further down, but don't see the obvious mapping.  I don't see anything technically wrong here, and depending on time pressure it may not be worth a major overhaul.

2023-02-09 20:00 UTC, rheslop commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Prepare your environment for upgrade from Red Hat OpenShift Container Platform v4.8 to v4.10. STF v1.5 only supports Red Hat OpenShift Container Platform v4.10.
```suggestion
* Prepare your environment for upgrade from Red Hat OpenShift Container Platform v4.8 to the supported version, v4.10.
```

2023-02-09 20:05 UTC, rheslop commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +Install the Service Telemetry Framework (STF) v1.5 Operators and the Certificate Manager for OpenShift Operator on your Red Hat OpenShift Container Platform v4.10 environment. STF v1.5 only supports
```suggestion
Install the Service Telemetry Framework (STF) v1.5 Operators and the Certificate Manager for OpenShift Operator. STF v1.5 only supports Red Hat OpenShift Container Platform v4.10. Installing STF into disconnected or restricted network environments is unsupported.
```
Assuming the reader will know they are installing this on RHOCP. The next sentence states the version requirement. Just cleaning up a bit, feel free to ignore if this makes anything less clear.

2023-02-09 20:27 UTC, leifmadsen commented
I'm noting here that once the review is complete here, we'll need to do a round of variable replacement so that the values are dynamic. There are also a few sections that need to get wrapped in `ifdef` as well because some sections are not applicable for all versions of RHOSP.

2023-02-09 20:29 UTC, leifmadsen requested changes
I'm just applying a review rejection for now so that we can come back and apply the variables after the content review is ready to go.

2023-02-09 20:51 UTC, csibbitt requested changes
I'm not sure I got all the missing attributes; maybe a fresh copy with the existing ones fixed would help, then I could at least `grep` locally.

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +:_content-type: PROCEDURE
I've not noticed this attribute before. I see it used only one other place in our docs before this PR, but you've used them consistently here. Are they necessary, and if so, should we add them to all the other files?

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +After you upgrade to Service Telemetry Framework (STF) v1.5, the CA certificate for AMQ Interconnect regenerates. In STF v1.4 the CA certificate for AMQ Interconnect is valid for three months and mus
```suggestion
After you upgrade to Service Telemetry Framework (STF) v1.5, the CA certificate for {MessageBus} regenerates. In STF v1.4 the CA certificate for {MessageBus} is valid for three months and must be updated periodically in {OpenStack} ({OpenStackShort}). In STF v1.5, the generated certificates are valid for 8 years by default.
```

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +Install the Service Telemetry Framework (STF) v1.5 Operators and the Certificate Manager for OpenShift Operator on your Red Hat OpenShift Container Platform v4.10 environment. STF v1.5 only supports
`{OpenShift}`

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +* For more information about how to update the CA certificate in your RHOSP environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/service_telemetry
```suggestion
* For more information about how to update the CA certificate in your {OpenStackShort} environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/service_telemetry_framework_1.5/assembly-renewing-the-amq-interconnect-certificate_assembly#proc-updating-the-amq-interconnect-ca-certificate_assembly-renewing-the-amq-interconnect-certificate[Updating the AMQ Interconnect CA certificate]
```

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +* For more information about how to update the CA certificate in your RHOSP environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/service_telemetry
The link also probably shouldn't be explicit like this, but be an internal reference, right?

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_upgrading-red-hat-openshift-container-platform-to-v4-10.adoc
> +For more information about upgrading your Red Hat OpenShift Container Platform from v4.8 to v4.10, see link:https://docs.openshift.com/container-platform/4.8///updating/index.html[Updating clusters o
```suggestion
For more information about upgrading your {OpenShift} from v4.8 to v4.10, see link:https://docs.openshift.com/container-platform/4.8///updating/index.html[Updating clusters overview ].
```

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +You must remove AMQ Certificate Manager and replace it with Certificate Manager for Red Hat OpenShift Container Platform when you upgrade Service Telemetry Framework (STF) v1.4 to STF v1.5. You must
`{OpenShift}` as well here

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Back up your data. There is an outage during the Red Hat OpenShift Container Platform upgrade. You cannot reconfigure the `ServiceTelemetry` and `SmartGateway` objects during the Operators replacem
`{OpenShift}`

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Prepare your environment for upgrade from Red Hat OpenShift Container Platform v4.8 to v4.10. STF v1.5 only supports Red Hat OpenShift Container Platform v4.10.
`{OpenShift}`

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* The Red Hat OpenShift Container Platform cluster is fully connected. STF does not support disconnected or restricted network clusters.
```suggestion
* The {OpenShift} cluster is fully connected. STF does not support disconnected or restricted network clusters.
```

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +. Upgrading the Red Hat OpenShift Container Platform to v4.10
```suggestion
. Upgrading the {OpenShift} to v4.10
```

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +. Optional: For information on how to re-subscribe to the Grafana Operator, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/service_telemetry_framework_1.
Shouldn't this link be internal to the document like `<<setting-up-grafana-to-host-the-dashboard_assembly-advanced-features>>` (untested)

2023-02-09 20:51 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
> +Remove the Service Telemetry Framework (STF) v1.4 Operators and the AMQ Certificate Manager Operator from the Red Hat OpenShift Container Platform v4.8.
```suggestion
Remove the Service Telemetry Framework (STF) v1.4 Operators and the AMQ Certificate Manager Operator from the {OpenShift} v4.8.
```

2023-02-10 11:53 UTC, mickogeary commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Back up your data. There is an outage during the Red Hat OpenShift Container Platform upgrade. You cannot reconfigure the `ServiceTelemetry` and `SmartGateway` objects during the Operators replacem
```suggestion
* You have backed up your data. There is an outage during the {OpenShift} upgrade. You cannot reconfigure the `ServiceTelemetry` and `SmartGateway` objects during the Operators replacement.
```

2023-02-10 11:54 UTC, mickogeary commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +You must remove AMQ Certificate Manager and replace it with Certificate Manager for Red Hat OpenShift Container Platform when you upgrade Service Telemetry Framework (STF) v1.4 to STF v1.5. You must
You must remove AMQ Certificate Manager and replace it with Certificate Manager for {OpenShift} when you upgrade {Project} ({ProjectShort}) v1.4 to {ProjectShort} v1.5. You must remove the `ClusterServiceVersion` and `Subscription` objects for Smart Gateway Operator and Service Telemetry Operator in the `service-telemetry` namespace on your {OpenShift} environment. You must upgrade {OpenShift} from v4.8 to v4.10 before you re-enable the operators that you removed.

2023-02-10 12:36 UTC, mickogeary commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +You must remove AMQ Certificate Manager and replace it with Certificate Manager for Red Hat OpenShift Container Platform when you upgrade Service Telemetry Framework (STF) v1.4 to STF v1.5. You must
How about I change that to:

To upgrade {Project} ({ProjectShort}) v1.4 to {ProjectShort} v1.5, you must complete the following steps:

* Replace AMQ Certificate Manager with Certificate Manager.

* Remove the `ClusterServiceVersion` and `Subscription` objects for Smart Gateway Operator and Service Telemetry Operator in the `service-telemetry` namespace on your {OpenShift} environment.

* Upgrade {OpenShift} from v4.8 to v4.10.

* Re-enable the operators that you removed.

* Update the {MessageBus} CA Certificate on {OpenStack}({OpenStackShort}).



and remove the procedure part at the bottom of that module, as there looks like some repetition otherwise

2023-02-10 15:19 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +. Create the Service Telemetry Operator subscription to manage the STF instances:
```suggestion
. Create the Service Telemetry Operator subscription to manage the {ProjectShort} instances:
```

2023-02-10 15:19 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +. Subscribe to the `cert-manager` Operator with the `redhat-operators` `CatalogSource`:
```suggestion
. Subscribe to the `cert-manager` Operator with the `redhat-operators` CatalogSource:
```

2023-02-10 15:19 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +. Optional: Re-subscribe to the Grafana Operator. For information, see: test xref:setting-up-grafana-to-host-the-dashboard_assembly-advanced-features[].
```suggestion
. Optional: Re-subscribe to the Grafana Operator. For more information, see: test xref:setting-up-grafana-to-host-the-dashboard_assembly-advanced-features[].
```

2023-02-10 15:20 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-amq-certificate-manager-operator.adoc
> +. Verify the AMQ Certificate Manager Operator deployment is not running:
```suggestion
. Verify that the AMQ Certificate Manager Operator deployment is not running:
```

2023-02-10 15:20 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
> +. Remove the Service Telemetry Operator
```suggestion
. Remove the Service Telemetry Operator.
```

2023-02-10 15:21 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
> +. Remove the Smart Gateway Operator
```suggestion
. Remove the Smart Gateway Operator.
```

2023-02-10 15:21 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
> +. Remove the AMQ Certificate Manager Operator
```suggestion
. Remove the AMQ Certificate Manager Operator.
```

2023-02-10 15:21 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
> +. Remove the Grafana Operator
```suggestion
. Remove the Grafana Operator.
```

2023-02-10 15:21 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
> +For more information about removing Operators from the {OpenShift}, see link:https://docs.openshift.com/container-platform/4.8///operators/admin/olm-deleting-operators-from-cluster.html[Deleting Oper
```suggestion
* For more information about removing Operators from {OpenShift}, see link:https://docs.openshift.com/container-platform/4.8///operators/admin/olm-deleting-operators-from-cluster.html[Deleting Operators from a cluster].
```

2023-02-10 15:24 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +* For more information about how to update the CA certificate in your {OpenStackShort} environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/servic
Rather than a link here, you should have the steps for the procedure. A one-step procedure with a link away from the user story is awkward and not accessible. 
@rheslop what do you think?

2023-02-10 15:25 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_upgrading-red-hat-openshift-container-platform-to-v4-10.adoc
> +
```suggestion
.Procedure
```

2023-02-10 15:29 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_upgrading-red-hat-openshift-container-platform-to-v4-10.adoc
> +For more information about upgrading your {OpenShift} from v4.8 to v4.10, see link:https://docs.openshift.com/container-platform/4.8/updating/index.html[Updating clusters overview].
```suggestion
* For more information about upgrading your {OpenShift} from v4.8 to v4.10, see link:https://docs.openshift.com/container-platform/4.8/updating/index.html[Updating clusters overview].
```

2023-02-10 15:59 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +* For more information about how to update the CA certificate in your {OpenStackShort} environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/servic
We had a look at the contents of the linked module, it's the same module but missing the intro and prereqs here for the upgrade user story.

2023-02-10 16:51 UTC, JoanneOFlynn2018 reviewed
Couple of things to check with Roger, other than that it looks good.

2023-02-13 14:03 UTC, rheslop commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +* For more information about how to update the CA certificate in your {OpenStackShort} environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/servic
I agree @JoanneOFlynn2018 , if the contents are exactly what are needed here, maybe there's a way to modularly re-use?

2023-02-13 15:08 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +* For more information about how to update the CA certificate in your {OpenStackShort} environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/servic
I might try to publish this content first and look at that after

2023-02-16 14:23 UTC, leifmadsen commented
Marking this as "needs-backport" and "1.5" since we probably want to import this sooner than later, but we don't want to have to merge `master` into `stable-1.5` until we're ready for that.

(I could do a check to see if there is any reason to _not_ do that, but want to know that we just need to be careful. This is more a note for myself when we are ready to get this imported.)

2023-02-16 15:56 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_upgrading-red-hat-openshift-container-platform-to-v4-10.adoc
> +* You removed the AMQ Certificate Manager Operator and Grafana Operator. You must remove the Operators before you upgrade Red Hat OpenShift Container Platform because the Operator APIs are incompatib
Heh yea this was copied in from however the OCP docs were rendering the link, which is why the extra slashes were present. Pretty ugly though :D

2023-02-16 15:57 UTC, leifmadsen commented
> I'm noting here that once the review is complete here, we'll need to do a round of variable replacement so that the values are dynamic. There are also a few sections that need to get wrapped in `ifdef` as well because some sections are not applicable for all versions of RHOSP.

I have proposed these changes against this branch in #447

2023-02-16 15:58 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +* For more information about how to update the CA certificate in your {OpenStackShort} environment, see: link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/17.0/html/servic
Alternatively just move all of this out of the procedures, drop the pre-requisites, and add an Additional Information section instead? (or keep prerequisites and just have additional information, but I feel like that style doesn't work either probably if I were to guess :))

2023-02-17 09:48 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Prepare your environment for upgrade from {OpenShift} v4.8 to the supported version, v4.10.
```suggestion
* You have prepared your environment for upgrade from {OpenShift} v4.8 to the supported version, v4.10.
```
Don't use present tense for prerequisites.

2023-02-17 09:50 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Remove the AMQ Certificate Manager before you upgrade {OpenShift}. Verify that no other Operators or workloads require the AMQ Certificate Manager in your environment.
```suggestion
* You have removed the AMQ Certificate Manager before you upgrade {OpenShift}. Verify that no other Operators or workloads require the AMQ Certificate Manager in your environment.
```

2023-02-17 09:51 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/assemblies/assembly_upgrading-service-telemetry-framework-to-version-1-5.adoc
> +* Remove the AMQ Certificate Manager before you upgrade {OpenShift}. Verify that no other Operators or workloads require the AMQ Certificate Manager in your environment.
```suggestion
```

This isn't a prereq to this user story, this is part of it.

2023-02-17 09:53 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +:_content-type: PROCEDURE
Yes you are correct! So going forward we should drop ":_content-type: PROCEDURE" from our docs, it's not a priority obviously but it might reduce future confusion.

@mickogeary

2023-02-17 09:54 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +* Your {OpenShift} environment network is fully-connected.
```suggestion
* Your {OpenShift} environment network is fully connected.
```
Global comment:
fully connected is definitely not hyphenated.

2023-02-17 09:56 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_installing-the-service-telemetry-framework-v1-5-operators.adoc
> +. Optional: Re-subscribe to the Grafana Operator. For more information, see xref:setting-up-grafana-to-host-the-dashboard_assembly-advanced-features[].
```suggestion
. Optional: Resubscribe to the Grafana Operator. For more information, see xref:setting-up-grafana-to-host-the-dashboard_assembly-advanced-features[].
```

2023-02-17 09:56 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-framework-v1-4-operators.adoc
> +* For more information about removing Operators from the {OpenShift}, see link:https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html[Deleting Oper
```suggestion
* For more information about removing Operators from the {OpenShift}, see link:https://docs.openshift.com/container-platform/4.8/operators/admin/olm-deleting-operators-from-cluster.html[Deleting Operators from a cluster].
```

2023-02-17 09:59 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-service-telemetry-operator.adoc
> +
```suggestion
As part of upgrading your {Project} ({ProjectShort}) installation, you must remove the Service Telemetry Operator in the `service-telemetry` namespace on your {OpenShift} environment.
```
Every module must have an introduction for SEO.

2023-02-17 10:00 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_removing-the-smart-gateway-operator.adoc
> +
Same thing here, insert a short introduction for SEO.

2023-02-17 10:02 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_updating-the-amq-interconnect-ca-certificate-on-red-hat-openstack-platform.adoc
> +After you upgrade to {Project} ({ProjectShort}) v1.5, the CA certificate for {MessageBus} regenerates. In {ProjectShort} v1.4 the CA certificate for {MessageBus} is valid for three months and must be
```suggestion
After you upgrade to {Project} ({ProjectShort}) 1.5, the CA certificate for {MessageBus} regenerates. In {ProjectShort} 1.4, the CA certificate for {MessageBus} is valid for three months and must be updated periodically in {OpenStack} ({OpenStackShort}). In {ProjectShort} 1.5, the generated certificates are valid for the lifetime of the {OpenStackShort} lifecycle, which is 70080 hours by default.
```

Sometimes it's v1.x and sometimes it's 1.x. For consistency, drop the use of v1.x

2023-02-17 10:03 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_upgrading-red-hat-openshift-container-platform-to-v4-10.adoc
> += Upgrading {OpenShift} to v4.10
```suggestion
= Upgrading {OpenShift} to 4.10
```

2023-02-17 10:03 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_upgrading-red-hat-openshift-container-platform-to-v4-10.adoc
> +[id="upgrading-red-hat-openshift-container-platform-to-v4-10_{context}"]
```suggestion
[id="upgrading-red-hat-openshift-container-platform-to-4-10_{context}"]
```

YOu'll need to update the actual file name also.

2023-02-17 10:06 UTC, JoanneOFlynn2018 submitted a review, later dismissed
Hi Michael, 
I finished my review and requested a few changes. Nothing major.

2023-02-17 14:20 UTC, merged