Expose ability to set certificate renewal target times
infrawatch/documentation pull request #453
Opened 2023-03-09 18:19 UTC by vkmc

Expose the duration value in STO to allow better control of the default certificate renewal times.

2023-03-09 19:21 UTC, leifmadsen requested changes
A few minor things, but this is great first pass

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +Default value is `70128h`.
```suggestion
Default value is `70080h`.
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +Default value is `70128h`.
```suggestion
Default value is `70080h`.
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +In order to modify these you must follow a procedure similar to the one present in xref:xref:assembly-renewing-the-amq-interconnect-certificate_assembly[].
```suggestion
In order to modify these you must follow a procedure similar to the one present in xref:assembly-renewing-the-amq-interconnect-certificate_assembly[]
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +The `certificates` parameter for ElasticSearch is part of the `backends.events.elasticsearch` definition and is configured in the `ServiceTelemetry` object:
```suggestion
The `certificates` parameter for Elasticsearch is part of the `backends.events.elasticsearch` definition and is configured in the `ServiceTelemetry` object:
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +The following procedure is valid for greenfield {Project} ({ProjectShort}) deployments.
```suggestion
The following procedure is valid for new {Project} ({ProjectShort}) deployments.
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> ++
```suggestion
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +In this example, set Elasticsearch endpoint certificates duration to 3 years by setting `endpointCertDuration` to `26280h`
```suggestion
For example, set the Elasticsearch endpoint certificate duration to 3 years by setting `endpointCertDuration` to `26280h`
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +and set QDR CA Certificates duration to 10 years by setting `caCertDuration` to `87600h`.
```suggestion
and set QDR CA certificate duration to 10 years by setting `caCertDuration` to `87600h`.
```

2023-03-09 19:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +Keep the default for the other certificates (CA certificates for Elasticsearch and endpoint certificates for QDR will keep the value of 8 years):
```suggestion
Keep the default value for the other certificates (CA certificate for Elasticsearch and endpoint certificate for QDR):
```

2023-03-09 19:27 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/assemblies/assembly_advanced-features.adoc
> +
```suggestion
//TLS Certificates duration
ifdef::include_when_13,include_when_17[]
include::../modules/con_tls-certificates-duration.adoc[leveloffset=+1]
include::../modules/proc_configuring-tls-certificates-duration.adoc[leveloffset=+2]
endif::include_when_13,include_when_17[]
```

2023-03-09 19:27 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/assemblies/assembly_advanced-features.adoc
> +
Certificate controls are only necessary for RHOSP 13 and 17 (not done in RHOSP 16 due to older metrics_qdr version than what is shipped in 13 and 17).

2023-03-10 14:57 UTC, leifmadsen approved these changes
Two very minor things, but this looks great. Thanks!

2023-03-10 14:57 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +NOTE:: Once created the `ServiceTelemetry` object, the required certificates and their secrets for {Project} ({ProjectShort}) are created.
```suggestion
NOTE:: Once created the `ServiceTelemetry` object, the required certificates and their secrets for {ProjectShort} are created.
```

2023-03-10 14:57 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +NOTE:: Once created the `ServiceTelemetry` object, the required certificates and their secrets for {Project} ({ProjectShort}) are created.
STF was defined in the intro, so you can use ProjectShort everywhere after in the same procedure.

2023-03-10 14:57 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +The following procedure is valid for new {Project} ({ProjectShort}) deployments.
```suggestion
The following procedure is valid for new {ProjectShort} deployments.
```

2023-03-13 14:31 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +modify the `ServiceTelemetry` object and configure the `certificates` parameters.
```suggestion
To configure the duration of the TLS certificates that you use for the connections with
Elasticsearch and {MessageBus} in {Project} ({ProjectShort}),
modify the `ServiceTelemetry` object and configure the `certificates` parameters.

2023-03-13 14:33 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +certificates duration:
```suggestion
You can use the the following sub-parameters of the `certificates` parameter to configure the
duration of the certificate :
```

2023-03-13 14:35 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +endpointCertDuration:: The requested 'duration' (i.e. lifetime) of the endpoint Certificate.
```suggestion
endpointCertDuration:: The requested 'duration' or lifetime of the endpoint Certificate.
```

2023-03-13 14:38 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +Minimum accepted duration is 1 hour. Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
```suggestion
The minimum valid duration is 1 hour. The value must be in units accepted by Go time.ParseDuration. For more information about Go ParseDuration, see:  https://golang.org/pkg/time/#ParseDuration.
```

2023-03-13 14:39 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +Default value is `70080h`.
```suggestion
The default value is `70080h`.
```

2023-03-13 14:43 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +Minimum accepted duration is 1 hour. Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
```suggestion
The minimum valid duration is 1 hour. You must set a value in units that are accepted by Go time.ParseDuration. For more information about Go ParseDuration, see:  https://golang.org/pkg/time/#ParseDuration.
```

2023-03-13 14:46 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +NOTE:: Certificates are by default long lived considering a subset of them are expected to be copied in the {OpenStack}
```suggestion
NOTE:: The default duration of certificates is long, because you usually copy a subset of them in the {OpenStack} deployment when the certificates renew.
```

2023-03-13 14:56 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +* Verify you don't have an instance of Service Telemetry Operator already deployed.
```suggestion
* You didn't deploy an instance of Service Telemetry Operator already.
```

2023-03-13 14:57 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +NOTE:: Once created the `ServiceTelemetry` object, the required certificates and their secrets for {Project} ({ProjectShort}) are created.
When you create the `ServiceTelemetry` object, the required certificates and their secrets for {ProjectShort} are also created.

2023-03-13 14:59 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +In order to modify these you must follow a procedure similar to the one present in xref:assembly-renewing-the-amq-interconnect-certificate_assembly[]
```suggestion
For more information about how to modify the certificates and the secrets, see: xref:assembly-renewing-the-amq-interconnect-certificate_assembly[]
```

2023-03-13 15:03 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +To override the duration of the TLS certificates, define which certificate you want to override.
```suggestion
To edit the duration of the TLS certificates, you can set the Elasticsearch `endpointCertDuration`, for example `26280h` for 3 years, and set the QDR `caCertDuration`, for example `87600h` for 10 years.
```

2023-03-13 15:05 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +. Verify that the desired expiry date appears in the certificates:
```suggestion
. Verify that the expiry date for the certificates is correct:
```

2023-03-13 15:08 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +modify the `ServiceTelemetry` object and configure the `certificates` parameters.
```suggestion
To configure the duration of the TLS certificates that you use for the connections with
Elasticsearch and {MessageBus} in {Project} ({ProjectShort}),
modify the `ServiceTelemetry` object and configure the `certificates` parameters.
```

2023-03-13 15:11 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +certificates duration:
```suggestion
You can configure the duration of the certificate with the following sub-parameters of the `certificates` parameter:
```

2023-03-13 15:15 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +For this purpose, modify the `ServiceTelemetry` object and configure the `certificates` parameter.
```suggestion
To configure the duration of the TLS certificates to use with {Project} ({ProjectShort}), modify the `ServiceTelemetry` object and configure the `certificates` parameter.
```

2023-03-13 15:18 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_configuring-tls-certificates-duration.adoc
> +Keep the default value for the other certificates (CA certificate for Elasticsearch and endpoint certificate for QDR will keep the value of 8 years):
```suggestion
You can use the default value of 8 years for the CA certificate for Elasticsearch and endpoint certificate:
```

2023-03-13 15:24 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +Minimum accepted duration is 1 hour. Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
For more information about Go time.ParseDuration [...]

2023-03-13 15:25 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +Minimum accepted duration is 1 hour. Value must be in units accepted by Go time.ParseDuration https://golang.org/pkg/time/#ParseDuration.
For more information about Go time.ParseDuration [...]

2023-03-13 15:26 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +The `certificates` parameter for Elasticsearch is part of the `backends.events.elasticsearch` definition and is configured in the `ServiceTelemetry` object:
Needs ending period or colon. I don't believe we just leave these sentences open ended.

2023-03-13 15:29 UTC, leifmadsen approved these changes

2023-03-13 15:30 UTC, leifmadsen commented
Well that's odd.... tried using the batch feature but I don't think it worked...

2023-03-13 18:23 UTC, vkmc commented
Looks way better with the redaction updates :) thanks!

2023-03-16 12:47 UTC, merged