mg master 1195 add OSPdO content incl 3 new modules
infrawatch/documentation pull request #461
Opened 2023-05-05 15:06 UTC by mickogeary

2023-05-05 15:17 UTC, rheslop commented on doc-Service-Telemetry-Framework/modules/proc_deploying-the-overcloud-for-director-operator.adoc
> +. Add the `metrics/ceilometer-write-qdr.yaml` and `metrics/qdr-edge-only.yaml` environment files as values for the `heatEnvs` parameter, save your edits and close the `OpenStackConfigGenerator` custo
```suggestion
. Add the `metrics/ceilometer-write-qdr.yaml` and `metrics/qdr-edge-only.yaml` environment files as values for the `heatEnvs` parameter. Save your edits, and close the `OpenStackConfigGenerator` custom resource:
```

I added a colon at the end as well, but the NOTE admonition gets in the way. Would it make sense to move it down past the example?

2023-05-08 13:11 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-red-hat-openstack-platform-overcloud-for-stf-using-director-operator.adoc
> +When you deploy the {OpenStack} ({OpenStackShort}) overcloud deployment using director Operator, you must configure the data collectors and the data transport to {Project} ({ProjectShort}).
Something about this seems off... 

> you must configure the data collectors and the data transport to {Project} ({ProjectShort}).

I think perhaps the "to {Project}" maybe should be "for {Project}"?

2023-05-08 13:12 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-red-hat-openstack-platform-overcloud-for-stf-using-director-operator.adoc
> +* You are familiar with deploying {OpenStackShort} with the {OpenStackShort} director Operator.
```suggestion
* You are familiar with deploying and managing {OpenStackShort} with the {OpenStackShort} director Operator.
```

2023-05-08 13:24 UTC, leifmadsen requested changes
Added some comments and updates to links to not have them hard-coded to the RHOSP versions. I also am thinking maybe wrapping the top level includes for this so it's generated only downstream. I'm not sure how readily available OSPdO is even upstream, and it's not important to show this in the upstream documentation for STF, in my opinion.

2023-05-08 13:24 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-the-stf-connection-for-director-operator-for-the-overcloud.adoc
> +. Add your `stf-connectors.yaml` configuration to the `heat-env-config-deploy ConfigMap`, appropriate to your environment, save your edits and close the file:
```suggestion
. Add your `stf-connectors.yaml` configuration to the `heat-env-config-deploy` ConfigMap, appropriate to your environment, save your edits and close the file:
```

2023-05-08 13:24 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-the-stf-connection-for-director-operator-for-the-overcloud.adoc
> +* For more information about the `stf-connectors.yaml` environment file, see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.2/html/service_telemetry_framework_1.5/as
```suggestion
* For more information about the `stf-connectors.yaml` environment file, see xref:configuring-the-stf-connection-for-the-overcloud_assembly-completing-the-stf-configuration[].
```

2023-05-08 13:24 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-the-stf-connection-for-director-operator-for-the-overcloud.adoc
> +* For more information about adding heat templates to a {OpenStack} director Operator deployment, see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.2/html/rhosp_dir
```suggestion
* For more information about adding heat templates to a {OpenStack} director Operator deployment, see link:{defaultURL}/rhosp_director_operator_for_openshift_container_platform/assembly_adding-heat-templates-and-environment-files-with-the-director-operator_rhosp-director-operator#doc-wrapper[Adding heat templates and environment files with the director Operator]
```

2023-05-08 13:24 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-the-overcloud-for-director-operator.adoc
> +* For more information about getting the latest `OpenStackConfigVersion`, see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.2/html/rhosp_director_operator_for_opens
```suggestion
* For more information about getting the latest `OpenStackConfigVersion`, see link:{defaultURL}/rhosp_director_operator_for_openshift_container_platform/assembly_configuring-overcloud-software-with-the-director-operator_rhosp-director-operator#proc_obtain-the-latest-openstackconfigversion.adoc_assembly_configuring-overcloud-software-with-the-director-operator[Obtain the latest OpenStackConfigVersion]
```

2023-05-08 13:24 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-the-overcloud-for-director-operator.adoc
> +* For more information about applying the overcloud configuration with director Operator, see link:https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/16.2/html/rhosp_director_op
```suggestion
* For more information about applying the overcloud configuration with director Operator, see link:{defaultURL}/rhosp_director_operator_for_openshift_container_platform/assembly_configuring-overcloud-software-with-the-director-operator_rhosp-director-operator#proc_applying-overcloud-configuration-with-the-director-operator_assembly_configuring-overcloud-software-with-the-director-operator[Applying overcloud configuration with the director Operator]
```

2023-05-11 12:46 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-red-hat-openstack-platform-overcloud-for-stf-using-director-operator.adoc
> +When you deploy the {OpenStack} ({OpenStackShort}) overcloud deployment using director Operator, you must configure the data collectors and the data transport to {Project} ({ProjectShort}).
```suggestion
When you deploy the {OpenStack} ({OpenStackShort}) overcloud deployment using director Operator, you must configure the data collectors and the data transport for {Project} ({ProjectShort}).
```

2023-05-11 12:47 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-red-hat-openstack-platform-overcloud-for-stf-using-director-operator.adoc
> +. xref:dproc_deploying-the-overcloud-for-director-operator[Deploying the overcloud for director operator]
```suggestion
. xref:proc_deploying-the-overcloud-for-director-operator[Deploying the overcloud for director operator]
```

2023-05-11 13:09 UTC, leifmadsen approved these changes
Worked this with Michael today, and we're happy to land this.

2023-05-11 13:12 UTC, merged