Initial pass for external ES
infrawatch/documentation pull request #483
Opened 2023-08-15 17:08 UTC by csibbitt

- Adjusting all language that refers to ECK or to STF deploying ES
- Adjusted procedures to refer to new parameters and step for creating required secrets
- Removed sections on managing ES server certificate lifetimes
- Removed ES + ECK from example outputs

2023-08-15 17:08 UTC, csibbitt commented
Putting this out for early feedback. I'd like to at least add the following:
* Deprecation notice for old parameters/functionality
* A section on migration procedures

2023-08-16 17:20 UTC, leifmadsen requested changes
First pass of this. Looks really good! Just some minor bits.

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kuberneters Operator (ECK). This functionality is deprecated as of {ProjectShort} 1.5.
```suggestion
Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kuberneters Operator (ECK). This functionality is deprecated as of {ProjectShort} 1.5.3. Future versions of Service Telemetry Operator will continue to support forwarding to an existing Elasticsearch instance (which can be one deployed by ECK), but will not manage the creation of Elasticsearch objects. When upgrading an {ProjectShort} deployment, any existing Elasticsearch object and deployment will remain intact, but will no longer be managed by {ProjectShort}.
```

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kuberneters Operator (ECK). This functionality is deprecated as of {ProjectShort} 1.5.
As part of documentation style, we don't promise anything in writing, so I've removed that bit, but otherwise this looks good thanks!

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
>  To enable Elasticsearch as a storage back end for events, you must configure the `ServiceTelemetry` object.
```suggestion
To enable events forwarding to Elasticsearch as a storage back end, you must configure the `ServiceTelemetry` object.
```

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +          hostUrl: https://external-elastic-http.domain:9200
I think it might be worth to have this value match what we would have deployed previously to make it simpler for someone to migrate from managed-ES to external-ES with their existing ECK-based ES deployment.

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +. Create the secret named in the `userSecretName`` parameter to store the basic auth credentials
```suggestion
. Create the secret named in the `userSecretName` parameter to store the basic auth credentials
```

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kuberneters Operator (ECK). This functionality is deprecated as of {ProjectShort} 1.5.
Also since this comment is a single line, I think you can just do `NOTE: <single_line_note>`. For admonition blocks like this, the content will usually get wrapped like so:

```
[NOTE]
====
Some sentence.

Another sentence.
====
```

This probably works fine in this case, but if someone adds another paragraph or something in the future it can cause generation problems you might not notice.

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-observability-strategy.adoc
> +To configure {ProjectShort} to skip the deployment of storage, visualization, and alerting backends, add `observabilityStrategy: none` to the ServiceTelemetry spec. In this mode, only {MessageBus} ro
I can't remember if this was tested or not, but I feel like some of the work you added for external ES might allow for the deployment of events SGs now in this mode? Felt like we looked at this before, but I can't remember what the result was now.

If you happen to remember then this could be updated otherwise that seems like a problem for another time.

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_creating-a-servicetelemetry-object-in-openshift.adoc
> +NOTE: If you set the `backends.events.elasticsearch.enabled` parameter to `true`, the notification Smart Gateways report `Error` and `CrashLoopBackOff` if they are unable to connect to the Elasticsea
Hrmmm now I've seen NOTE:: and NOTE: (dual vs singular colons) and I'm not sure which one is correct...

<looks it up>

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions

Seems as if single-colon is correct. Will note in other section.

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
>  NOTE:: The default duration of certificates is long, because you usually copy a subset of them in the {OpenStack} deployment when the certificates renew. For more information about the QDR CA Certifi
```suggestion
NOTE: The default duration of certificates is long, because you usually copy a subset of them in the {OpenStack} deployment when the certificates renew. For more information about the QDR CA Certificate renewal process, see xref:assembly-renewing-the-amq-interconnect-certificate_assembly[]
```

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
>  NOTE:: The default duration of certificates is long, because you usually copy a subset of them in the {OpenStack} deployment when the certificates renew. For more information about the QDR CA Certifi
From https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#admonitions which references single-colon vs double-colon for admonitions.

2023-08-16 17:20 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-to-the-openshift-environment.adoc
> -. To store events in Elasticsearch, you must enable the Elastic Cloud on Kubernetes (ECK) Operator by using the certified-operators CatalogSource:
You can revert the contents of this entire file because I'll cover it in #484 (just FYI).

2023-08-22 14:06 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kuberneters Operator (ECK). This functionality is deprecated as of {ProjectShort} 1.5.
I hadn't rendered it yet, so I'll just implement the multi-line version, otherwise I'll have to remember to change it in the future if we expand it. Thanks!

2023-08-22 14:21 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +          hostUrl: https://external-elastic-http.domain:9200
Users who are migrating won't need to touch it though, or even really know about the parameter at all. The default value (which is shown elsewhere in these docs) suggests that the ES instance should be deployed in the same OCP namespace as STF; something I'd rather discourage. So I thought this example would better emphasize that this points to an externally managed ES, and not something that lives with STF.

2023-08-22 14:21 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +. Create the secret named in the `userSecretName`` parameter to store the basic auth credentials
See? I told you I hadn't rendered it yet ;)

2023-08-22 14:44 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_configuring-observability-strategy.adoc
> +To configure {ProjectShort} to skip the deployment of storage, visualization, and alerting backends, add `observabilityStrategy: none` to the ServiceTelemetry spec. In this mode, only {MessageBus} ro
Yea if it works for both SG types, I think it's worth mentioning that briefly.

2023-08-22 16:27 UTC, leifmadsen approved these changes
Two super minor tweaks, but looks good!

2023-08-22 16:27 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kuberneters Operator (ECK). This functionality is deprecated as of {ProjectShort} 1.5.
```suggestion
Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kubernetes Operator (ECK). Elasticsearch management functionality is deprecated as of {ProjectShort} 1.5.3. Future versions of Service Telemetry Operator will continue to support forwarding to an existing Elasticsearch instance (which can be deployed and managed by ECK), but will not manage the creation of Elasticsearch objects. When upgrading an {ProjectShort} deployment, any existing Elasticsearch object and deployment will remain intact, but will no longer be managed by {ProjectShort}.
```

2023-08-22 16:27 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_primary-parameters-of-the-servicetelemetry-object.adoc
> +Older versions of {ProjectShort} would manage Elasticsearch objects for the community supported Elastic Cloud on Kuberneters Operator (ECK). This functionality is deprecated as of {ProjectShort} 1.5.
Kuberneters!

2023-08-22 16:27 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_tls-certificates-duration.adoc
> +NOTE: The default duration of certificates is long, because you usually copy a subset of them in the {OpenStack} deployment when the certificates renew. For more information about the QDR CA Certific
```suggestion
NOTE: The default duration of certificates is long, because you usually copy a subset of them in the {OpenStack} deployment when the certificates renew. For more information about the QDR CA Certificate renewal process, see xref:assembly-renewing-the-amq-interconnect-certificate_assembly[].
```

2023-08-22 16:27 UTC, merged