mg_master_RHOSPDOC-1380_chunk-installation-procedure
infrawatch/documentation pull request #492
Opened 2023-09-19 18:17 UTC by mickogeary

I separated these into separate adoc files

    Deploying Observability Operator
    Deploying Certificate Manager for OpenShift Operator
    Deploying Service Telemetry Operator

by creating these files:
- "Deploying Certificate Manager for OpenShift Operator"
modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
- "Deploying Service Telemetry Operator"
modules/proc_deploying-service-telemetry-operator.adoc

2023-09-19 18:24 UTC, leifmadsen requested changes
Looks good so far! I think you also need to break out the Observability Operator procedure as well though.

2023-09-20 13:44 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-to-the-openshift-environment.adoc
>  Deploy {Project} ({ProjectShort}) to collect and store {OpenStack} ({OpenStackShort}) telemetry.
@mickogeary I mean, I guess technically this is a concept module now? Not really even a concept, since it's just a header or whatever, but since there no procedures here, seems appropriate to rename perhaps? (doesn't really matter overall, but for consistency seems like this should be renamed?)

2023-09-20 13:44 UTC, leifmadsen approved these changes
I'm approving since it looks correct to me. I think the intro file could get renamed since it's not a procedure any more, but I'd not block merging on that.

2023-09-20 14:06 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-to-the-openshift-environment.adoc
>  Deploy {Project} ({ProjectShort}) to collect and store {OpenStack} ({OpenStackShort}) telemetry.
I'll rename it now

2023-09-20 17:41 UTC, leifmadsen commented
Once the rename shows up, I'm happy to see this land. Thanks!

2023-09-26 19:12 UTC, leifmadsen approved these changes

2023-09-26 19:14 UTC, merged