Update install guide for dependent operators
infrawatch/documentation pull request #513
Opened 2023-11-22 22:53 UTC by leifmadsen

Update the installation guide for dependent operators. Adds installation
instructions for Cluster Observability Operator and cert-manager for Red
Hat OpenShift using the latest channels available for those Operators.
The result is that deployment of observabilityStrategy: use_redhat is
now possible as the default installation method.

Related: STF-1636

2023-11-22 23:08 UTC, leifmadsen commented
TODO: I need to add a `.Prerequisites` section to the "Creating a ServiceTelemetry object in Red Hat OpenShift Container Platform" section which references both the COO and cert-manager installation steps.

2023-11-22 23:11 UTC, csibbitt requested changes

2023-11-22 23:11 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
> +In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of {ProjectShort} on v
```suggestion
In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of cert-manager on versions of {OpenShift} v4.14 and later must be installed from the `stable-v1` channel. For new installations of {ProjectShort} it is recommended to install cert-manager from the `stable-v1` channel.
```

2023-11-23 12:51 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
> +In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of {ProjectShort} on v
I would drop "continues to work and", and just have it as: "which is available until OpenShift v4.12."

2023-11-23 13:14 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
> +In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of {ProjectShort} on v
Nice catch, thanks!

2023-11-23 13:22 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
> +In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of {ProjectShort} on v
@mickogeary done

2023-11-23 15:11 UTC, csibbitt approved these changes

2023-11-23 15:22 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
> +In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of {ProjectShort} on v
"The cert-manager for Red Hat OpenShift (cert-manager) Operator must be pre-installed before creating an instance of {Project} ({ProjectShort})." is  passive. 

"You must install the cert-manager for Red Hat OpenShift (cert-manager) Operator before you create an instance of {Project} ({ProjectShort})." might be less passive.

2023-11-23 15:24 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
> +In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of {ProjectShort} on v
"Installations of {ProjectShort} on versions of {OpenShift} v4.14 and later must be installed from the `stable-v1` channel." is passive.
"Ensure that you install {ProjectShort} on versions of {OpenShift} v4.14 and later from the `stable-v1` channel." might be less passive.




 For new installations of {ProjectShort} it is recommended to install cert-manager from the `stable-v1` channel.

2023-11-23 15:25 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-certificate-manager-for-openshift-operator.adoc
> +In previous versions of {ProjectShort}, the only available cert-manager channel was `tech-preview` which continues to work and is available until OpenShift v4.12. Installations of {ProjectShort} on v
"For new installations of {ProjectShort} it is recommended to install cert-manager from the `stable-v1` channel." could maybe be dropped. It looks like it is saying the same thing as the previous sentence.

2023-11-23 15:48 UTC, merged