Update required resource permission reference
infrawatch/documentation pull request #528
Opened 2024-02-06 21:23 UTC by leifmadsen

Update the required resource permission reference to use the Grafana
Operator v5 group.

2024-02-07 23:06 UTC, csibbitt requested changes
We either need to change the code to match, or just leave this how it is

2024-02-07 23:06 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_accessing-uis-for-stf-components.adoc
> +{"namespace":"service-telemetry", "resource":"grafana", "group":"grafana.integreatly.org", "verb":"get"}
:x: Unfortunately this stuff is not automatic. The permission required to access grafana is controlled here[1], and it looks like it has not been updated.

[1] https://github.com/infrawatch/service-telemetry-operator/blob/164f0ca5d6a2b262efcc0ea2265ffc2ca1cd96e1/roles/servicetelemetry/templates/manifest_grafana.j2#L45

2024-02-08 01:25 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_accessing-uis-for-stf-components.adoc
> +{"namespace":"service-telemetry", "resource":"grafana", "group":"grafana.integreatly.org", "verb":"get"}
Thanks Chris, I'm glad I didn't just self-merge this :)

That's the Grafana v4 deployment manifest. I ended up creating another one here: https://github.com/infrawatch/service-telemetry-operator/blob/master/roles/servicetelemetry/templates/manifest_grafana_v5.j2#L64

The permission is correct there though I think?

2024-02-08 15:01 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_accessing-uis-for-stf-components.adoc
> +{"namespace":"service-telemetry", "resource":"grafana", "group":"grafana.integreatly.org", "verb":"get"}
Oh whoops, yes, it matches there, sorry. I overlooked that we have two now - it seems that they are chosen based on which API is available in the cluster? It might simplify documentation and support if they could be the same perms in both cases, but I'm unsure if you can add a sar for `"group":"grafana.integreatly.org"` if the new API isn't installed. Could also just standardize on the older version though it does seem less precisely targeted.

2024-02-08 19:13 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_accessing-uis-for-stf-components.adoc
> +{"namespace":"service-telemetry", "resource":"grafana", "group":"grafana.integreatly.org", "verb":"get"}
Yea I hear you. I'm not sure what would happen if someone didn't have the Grafana Operator v4 installed (I suspect some sort of failure?). It might not be a problem with someone who migrated, but in a greenfield installation (or if they cleaned out the old CRD) I'm also not sure what would happen.

I did end up testing both v4 and v5 operators, and they both worked. Unless there is a reason to flatten this down, I'd rather avoid having to stand everything up and test both operator versions again.

2024-02-08 19:16 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_accessing-uis-for-stf-components.adoc
> +{"namespace":"service-telemetry", "resource":"grafana", "group":"grafana.integreatly.org", "verb":"get"}
Also to answer your other question, yes the logic depends on which API interface is available. It looks for `grafana.integreatly.org` first (signals G-O v5) and then if that doesn't exist, looks for `integreatly.org` (G-O v4). If it finds the old API (after not finding the new API) then it will do what it did before.

2024-02-08 20:19 UTC, csibbitt commented on doc-Service-Telemetry-Framework/modules/proc_accessing-uis-for-stf-components.adoc
> +{"namespace":"service-telemetry", "resource":"grafana", "group":"grafana.integreatly.org", "verb":"get"}
> "I did end up testing both v4 and v5 operators"

Do you mean that you tested an account with the `"group":"grafana.integreatly.org"` permission against both operators? I'd not considered that the less specific "group" in the v4 SAR might still match when a user is given the more specific permission. If that's the case then this is totally fine by me.

2024-02-08 20:24 UTC, csibbitt approved these changes
If this works for v4 and v5, that's awesome. If it works just for v5, we will have this conversation to refer to if it ever comes up in a support context.

2024-02-08 20:24 UTC, merged

2024-02-08 20:28 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_accessing-uis-for-stf-components.adoc
> +{"namespace":"service-telemetry", "resource":"grafana", "group":"grafana.integreatly.org", "verb":"get"}
So to clarify:

* I installed Grafana Operator v4, and enabled dashboarding, which used the old template, and the old SAR: worked
* I removed Grafana Operator v4 and CRDs, and installed Grafana Operator v5, enabled dashboarding, which used the new template, and the new SAR configuration: worked

I then updated the documentation everywhere to just reference Grafana Operator v5, which is expected to be used in deployments now, with an expectation everyone needs to get on board. I have a backlog item to write a KBA to help migrate (remove then reinstall) to v5 Operator.