mg-master_RHOSPDOC-1200_STF-disconnected
infrawatch/documentation pull request #531
Opened 2024-02-16 17:23 UTC by mickogeary

Slightly changed section 2.4, added new procedure section 2.5 about STF disconnected

2024-02-16 20:33 UTC, vkmc requested changes
Good first pass, added some more details to the process.

2024-02-16 20:33 UTC, vkmc commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
Locate the generated manifests and apply them to the target OCP cluster. More details about this can be seen in https://docs.openshift.com/container-platform/4.14/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-updating-cluster-manifests_installing-mirroring-disconnected

2024-02-19 14:28 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* TBD
would another verification be that your STF is up-and-running and you cannot access external sites (disconnected), or that is not enough information?

2024-02-19 14:33 UTC, mickogeary commented on doc-Service-Telemetry-Framework/assemblies/assembly_preparing-your-ocp-environment-for-stf.adoc
>  * Ensure that you have a fully connected network environment. For more information, see xref:con-network-considerations-for-service-telemetry-framework_assembly-preparing-your-ocp-environment-for-stf
the only supported network environments are "fully-connected network environments and OpenShift-disconnected environments" - is this correct?
If that is true, then maybe: "Ensure that you are using a fully-connected or OpenShift-disconnected network environment." 
As you can see, I have that sentence ("Ensure that you have a fully connected network environment".) hidden for now. So either we can leave it out entirely, or mention the 2 supported types (or is there >2 ?)

2024-02-20 16:01 UTC, vkmc commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* TBD
Yes, I think we can add that as verification as well, perhaps more clear than checking the the catalog entries have been created correctly.

2024-02-20 16:21 UTC, leifmadsen requested changes

2024-02-20 16:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
```suggestion
```

2024-02-20 16:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
```suggestion
```

2024-02-20 16:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +NOTE: The manifests that you generate with `oc-mirror` produce catalogs with the full index name, such as `redhat-operator-index` instead of `redhat-operators` for `CatalogSource`. Ensure that you us
Please use xrefs to internal links so that it works across various versions. Never use `link` to self-linked documentation. It will result in the 16.2 documentation linking to the 17.1 documentation.

2024-02-20 16:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +You can use the `oc-mirror` tool to fetch the {ProjectShort} dependencies and add them to the {OpenShift} cluster mirror registry. For more information about installing the `oc-mirror` tool, see link
You need to replace `4.14` in the link with `{NextSupportedOpenShiftVersion}`

2024-02-20 16:21 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* A mirror registry so that the {OpenShift} cluster can access the required images. For more information about mirror registry for {OpenShift}, see link:https://access.redhat.com/documentation/en-us/
You need to replace `4.14` in the link with `{NextSupportedOpenShiftVersion}`

2024-02-22 12:58 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
Is this part of the note or is it the next step?

2024-02-26 17:34 UTC, vkmc commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
Next step

2024-02-26 17:36 UTC, vkmc commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* You have deployed {ProjectShort} and cannot access external networks.
I would rephrase this as

* You have deployed {ProjectShort} in a disconnected {OpenShiftShort} cluster

2024-02-26 18:01 UTC, vkmc approved these changes
LGTM, thanks a lot!

2024-02-26 19:15 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
I don't think this renders quite correctly when there are newlines between the +'s

2024-02-26 19:38 UTC, leifmadsen commented
I'm going through this now against a local build, and I'm going to have some comments. Please refrain from merging quite yet.

2024-02-26 20:18 UTC, leifmadsen requested changes

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> += Deploying {ProjectShort} on {OpenShiftShort}-disconnected environments
We've been specifically asked not to use "OCP" in the documentation, so there should really be no usage of {OpenShiftShort} in the STF docs. Not sure how strong a request that is now, but if you grep in the docs for that variable, you won't really find it in any spots. I suggest we remove it's usage from this module for consistency.

I would just write this to be `= Deploying {ProjectShort} in disconnected environments`.

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* {OpenShift}({OpenShiftShort}) Extended Update Support (EUS) version 4.12 or 4.14 deployed in a restricted network.
```suggestion
* {OpenShift} Extended Update Support (EUS) version 4.12 or 4.14 deployed in a restricted network.
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* A mirror registry so that the {OpenShift} cluster can access the required images. For more information about mirror registry for {OpenShiftShort}, see link:https://access.redhat.com/documentation/e
```suggestion
* A mirror registry so that the {OpenShift} cluster can access the required images. For more information about mirror registries, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/disconnected-installation-mirroring[Disconnected installation mirroring] in the {OpenShift} _Installing_ Guide.
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* All the {ProjectShort} dependencies are available in the {OpenShiftShort} cluster mirror registry.
```suggestion
* All the {ProjectShort} dependencies are available in the {OpenShift} cluster mirror registry. 
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +You can use the `oc-mirror` tool to fetch the {ProjectShort} dependencies and add them to the {OpenShiftShort} cluster mirror registry. For more information about installing the `oc-mirror` tool, see
```suggestion
You can use the `oc-mirror` tool to fetch the {ProjectShort} dependencies and add them to the {OpenShift} cluster mirror registry. For more information about installing the `oc-mirror` tool, see link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html-single/installing/index#installing-mirroring-disconnected[Mirroring images for a disconnected installation using the oc-mirror plugin] in the {OpenShift} _Installing_ guide.
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +. (Optional) If your mirror registry is not reachable, you can save the manifests and images that you fetched with `oc-mirror` and physically transfer them to the mirror registry and {OpenShiftShort}
```suggestion
. (Optional) If your mirror registry is not reachable, you can save the manifests and images that you fetched with `oc-mirror` and physically transfer them to the mirror registry and {OpenShift} cluster. Otherwise you can run `oc-mirror` and point to the mirror registry.  
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* mirror from disk to mirror.
I don't think you want periods ending these line items, and if you do, you should do it on all lines.

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +For more information about different oc-mirror scenarios, see: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/installing/disconnected-installation-mirroring
```suggestion
For more information about different oc-mirror scenarios, see: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/disconnected-installation-mirroring#mirroring-image-set-full[Mirroring an image set in a fully disconnected environment]
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +. Push the {ProjectShort} operators and their dependencies from the mirror registry and generate the manifest for the OCP cluster.
```suggestion
. Push the {ProjectShort} operators and their dependencies from the mirror registry and generate the manifest for the {OpenShift} cluster.
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
```suggestion
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
```suggestion
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
```suggestion
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +. Locate the generated manifests and apply them to the target OCP cluster. For more information, see: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.14/html/install
```suggestion
. Locate the generated manifests and apply them to the target {OpenShift} cluster. For more information, see: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/disconnected-installation-mirroring#oc-mirror-updating-cluster-manifests_installing-mirroring-disconnected[Configuring your cluster to use the resources generated by oc-mirror]
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +NOTE: The manifests that you generate with `oc-mirror` produce catalogs with the full index name, such as `redhat-operator-index` instead of `redhat-operators` for `CatalogSource`. Ensure that you us
Do not link to internal guides within STF with `link`. Please use `xref` and the `id` values with the assembly ID.

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
```suggestion
```

2024-02-26 20:18 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* You have deployed {ProjectShort} in a disconnected {OpenShiftShort} cluster and therefore cannot access external networks.
```suggestion
* You have deployed {ProjectShort} in a disconnected {OpenShift} cluster and therefore cannot access external networks.
```

2024-02-26 20:28 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* Continue to install {ProjectShort} as in a non-restricted network environment.
We have never used "Next steps" (as it was created after we started on STF documentation) so you can drop this. I believe the purpose is intended to link to next xref locations that would make sense to go to after you've done this procedure.

2024-02-26 20:29 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +////
If you don't have any links / reference material to give to the user, then you can simply remove this.

2024-02-27 13:50 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/con_network-considerations-for-service-telemetry-framework.adoc
> +You can deploy {Project} ({ProjectShort}) in fully-connected network environments or in {OpenShift}-disconnected environments. You cannot deploy {ProjectShort} in network proxy environments.
```suggestion
You can deploy {Project} ({ProjectShort}) in fully connected network environments or in {OpenShift}-disconnected environments. You cannot deploy {ProjectShort} in network proxy environments.
```

Nit. Page 119 of IBM SG

2024-02-27 13:57 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> += Deploying {ProjectShort} on {OpenShiftShort}-disconnected environments
I just checked this and we still do not use OCP in docs. @mickogeary how about deleting the attribute altogether from the attributes file? Should have done that myself long ago!

2024-02-27 13:59 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +. (Optional) If your mirror registry is not reachable, you can save the manifests and images that you fetched with `oc-mirror` and physically transfer them to the mirror registry and {OpenShiftShort}
Nit: 

Change (Optional) to Optional: 

Just updating formatting for optional step (pg 202 IBM SG)

2024-02-27 14:09 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> += Deploying {ProjectShort} on {OpenShiftShort}-disconnected environments
I opened this to cover the removal: https://github.com/infrawatch/documentation/pull/532

2024-02-27 14:15 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +.Adding {ProjectShort} dependencies to the mirror registry
Just read further down and now it definitely looks like another prereq

2024-02-29 10:07 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +////
+1

2024-02-29 10:09 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* You have deployed {ProjectShort} in a disconnected {OpenShiftShort} cluster and therefore cannot access external networks.
@mickogeary Not sure why this isn't in present tense. If it's a step, it must be in present tense. It reads like a prereq right now.

2024-02-29 10:12 UTC, JoanneOFlynn2018 commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +You can use the oc-mirror plugin differently, depending on your environment, such as:
```suggestion
You can use the `oc-mirror` plugin differently, depending on your environment, such as:
```

2024-02-29 15:51 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +* You have deployed {ProjectShort} in a disconnected {OpenShiftShort} cluster and therefore cannot access external networks.
It is a verification step

2024-03-01 15:24 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/con_manifest-overrides.adoc
> +The Service Telemetry Operator watches for a `ServiceTelemetry` manifest to load into {OpenShift}. The Operator then creates other objects in memory, which results in the dependent Operators creating
Looks like this file isn't even included and can be removed.

2024-03-01 15:25 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_overriding-a-managed-manifest.adoc
> +. To modify the `ServiceTelemetry` object, provide a manifest override parameter and the contents of the manifest to write to {OpenShift} instead of the defaults provided by {ProjectShort}.
This file isn't included any more. I removed it in #533 which is causing a conflict here. I will resolve it.

2024-03-05 17:09 UTC, leifmadsen requested changes
Couple comments still to resolve, but otherwise looks ok

2024-03-05 17:09 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/assemblies/assembly_preparing-your-ocp-environment-for-stf.adoc
> +////
If this is commented out, please remove it from the docs entirely.

2024-03-05 17:09 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +
@mickogeary have you built this locally and verified that everything renders as you expect?

2024-03-05 17:09 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +////
If you're going to comment out a section, please delete it.

2024-03-05 17:12 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +apiVersion: mirror.openshift.io/v1alpha2
Other examples in the STF guide usually provide these files with `oc create -f - <<EOF` type setups so that you can show the user how to get this applied to the cluster.

2024-03-05 17:12 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +. Locate the generated manifests and apply them to the target OCP cluster. For more information, see: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpe
Another use of short form OCP. Need to not use those.

2024-03-05 17:13 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +NOTE: The manifests that you generate with `oc-mirror` produce catalogs with the full index name, such as `redhat-operator-index` instead of `redhat-operators` for `CatalogSource`. Ensure that you us
```suggestion
NOTE: The manifests that you generate with `oc-mirror` produce catalogs with the full index name, such as `redhat-operator-index` instead of `redhat-operators` for `CatalogSource`. Ensure that you use the correct index name for the {ProjectShort} subscriptions. For more information, see: xref:deploying-stf-to-the-openshift-environment_assembly-installing-the-core-components-of-stf[]. For more information about customizing Operators with oc mirror, see the Red Hat Knowledgebase solution link:https://access.redhat.com/solutions/7016714[How to customize the catalog name and tags of Operators mirrored to the mirror registry using the oc mirror plugin.] 
```

2024-03-05 17:14 UTC, leifmadsen commented
Left a few more comments and suggested changes.

2024-03-05 18:34 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +For more information about different `oc-mirror` scenarios, see: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/discon
`see:` with a colon doesn't match our existing style.

Our style is more like this:

> For more information about STF life cycle and support status, see the [Service Telemetry Framework Supported Version Matrix](https://access.redhat.com/node/6225361).

2024-03-05 18:39 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +$ oc create -f - <<EOF
Sorry I was wrong about this. We should not do this.

I see 2 steps down we do this procedural step:

`$ oc-mirror --config imagesetconfig.yaml <mirror_registry_location>`

We should actually tell the user to write the contents to a file which we can use later.

If you look at something like here: https://infrawatch.github.io/documentation/#creating-the-base-configuration-for-stf_assembly-completing-the-stf-configuration

You can see that we create a procedural step to create the file (which is what we should do here) and then we reference the file later on when doing the actual command that needs that config file.

2024-03-05 18:39 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +For more information about different `oc-mirror` scenarios, see: link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{NextSupportedOpenShiftVersion}/html/installing/discon
If you search for `see:` you will find 3 instances of that in this file.

2024-03-05 18:42 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +////
```suggestion
```

2024-03-05 18:42 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +////
I'm still expecting this to be deleted, not left as a large comment.

2024-03-05 18:43 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +$ oc create -f - <<EOF
Remove the $ oc create -f - <<EOF ?

And add something like:

1. Log in to the undercloud host as the stack user.
 
2. Create a configuration file called ImageSetConfiguration.yaml in the /home/stack directory.

?

2024-03-05 18:49 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +$ oc create -f - <<EOF
Yea, except you won't have a `/home/stack` directory since this is being done against OpenShift. I'd just say something like "Create a file named imagesetconfig.yaml in a working directory with the following contents:" and then you can reference it 2 steps down.

2024-03-05 18:51 UTC, mickogeary commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +$ oc create -f - <<EOF
Replace:
. Create an `ImageSetConfiguration` resource to retrieve the {ProjectShort} dependencies:
with:
. Create a file named imagesetconfig.yaml in a working directory with the following contents:

and remove 

$ oc create -f - <<EOF

is this correct?

2024-03-05 18:53 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +$ oc create -f - <<EOF
Actually if you do it like we do in the other section, you'd just say something like this:

```
. Create an imagesetconfig.yaml file in your local working directory.
+
.imagesetconfig.yaml
[source,yaml,options="nowrap"]
----
<content>
----
```

2024-03-05 18:53 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/assemblies/assembly_preparing-your-ocp-environment-for-stf.adoc
> +////
```suggestion
```

2024-03-05 18:55 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/modules/proc_deploying-stf-on-openshift-disconnected-environments.adoc
> +----
```suggestion
. Create an `imagesetconfiguration.yaml` file in your local working directory.
+
.imagesetconfiguration.yaml
[source,yaml,options="nowrap",role="white-space-pre"]
----
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: ./
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
      - name: service-telemetry-operator
        channels:
          - name: stable-1.5
      - name: openshift-cert-manager-operator
        channels:
          - name: stable-v1
      - name: amq7-interconnect-operator
        channels:
          - name: 1.10.x
      - name: smart-gateway-operator
        channels:
          - name: stable-1.5
      - name: cluster-observability-operator
        channels:
          - name: development
----
```

2024-03-05 19:22 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/assemblies/assembly_preparing-your-ocp-environment-for-stf.adoc
> +////
```suggestion
```

2024-03-05 19:25 UTC, leifmadsen commented on doc-Service-Telemetry-Framework/assemblies/assembly_preparing-your-ocp-environment-for-stf.adoc
> +////
Oh no, this is the old comment. I'm removing it as staged vs keeping it in a comment block.

2024-03-05 19:26 UTC, leifmadsen approved these changes

2024-03-05 19:34 UTC, merged